### ISSUE TITLE
Probe disconnects without any error or warning

### ISSUE THREAD

**Issue by eagle00789** [PaesslerAG/PythonMiniProbe#9] opened 2015-05-18 10:09 UTC
A freshly installed probe stop running after a random time.
The logging (including debug log) doesn't report anything out of the ordinary

**Comment by eagle00789** [comment] 2015-05-18 10:09
Started a screen session with the probe manually started inside the screen session. Now it's just a matter of time until the probe crashes to see what goes wrong.

**Comment by konstantinpae** [comment] 2015-05-18 10:21
Have you checked the Log of the PRTG Core Server? Anything unusual there?
Also, are you able to reproduce the disconnect at will?

**Comment by eagle00789** [comment] 2015-05-18 13:16
There is no entry in the logfile as i already stated in my initial request.
I can't reproduce it at an instant, that's why i started a screen session with the probe manually started in the screen session to see if the probe dumps a tracelog to the console when it crashes.

**Comment by konstantinpae** [comment] 2015-05-18 13:37
@eagle00789 just talked to the interface developer on core side and he is looking into this right now. It seems that he might have found the flaw and is already working on fixing the same. I'll keep this issue open until a fix is out.

**Comment by eagle00789** [comment] 2015-05-18 13:50
Even though you think it's the core side, i will still monitor one of my probes to see what the tracelog prints when it fails (if it print's something at all), But still good to hear that a possible problem has already been found...

**Comment by eagle00789** [comment] 2015-05-21 10:45
my probe that i was monitoring with screen, just crashed and gave the following error on the console:

```
Traceback (most recent call last):
  File "probe.py", line 211, in <module>
    main()
  File "probe.py", line 182, in main
    logging.error("DATA Timeout: " + json_payload_data)
TypeError: cannot concatenate 'str' and 'list' objects
```

To fix this, replace line 182 in probe.py with the line below

```
logging.error("DATA Timeout: " + str(json_payload_data).strip('[]'))
```

This fix will be included in my next pullrequest i'm going to do on friday/saturday

**Comment by konstantinpae** [comment] 2015-05-22 08:45
@eagle00789 looking forward to the pull request. If done on the weekend it might get Monday until I can accept. Issue stays open therefore.

**Comment by konstantinpae** [comment] 2015-05-28 06:43
Closing this issue because of bugfix in [pull request](https://github.com/PaesslerAG/PythonMiniProbe/pull/11)

**Closed as completed by konstantinpae** 2015-05-28 06:43 UTC
